version: 2

models:
  - name: dim_region
    columns:
      - name: regionid
        tests:
          - unique
          - not_null
      - name: suburbid
        tests:
          - not_null

  - name: dim_property_type
    columns:
      - name: property_type
        tests:
          - unique
          - not_null
