{{ config(materialized='view') }}

WITH source_data AS (
    SELECT 
	CATEGORY ,
	REGIONID ,
	SUBURBID ,
	BATHROOMS ,
	BEDROOMS ,
	GEOLOCATION_LAT ,
	GEOLOCATION_LNG ,
	IS_NEW ,
	LAND_AREA ,
	LISTING_GROUP ,
	LISTING_ID ,
	LOUNGES ,
	PRICE_DISPLAY ,
	PROPERTY_TYPE ,
	REGION ,
	START_PRICE ,
	SUBURB,
	TITLE ,
	INSERTED_AT
    FROM {{ source('raw', 'trademe_property_listings') }}
)

SELECT
	CATEGORY ,
	REGIONID ,
	SUBURBID ,
	BATHROOMS ,
	BEDROOMS ,
	GEOLOCATION_LAT ,
	GEOLOCATION_LNG ,
	IS_NEW ,
	LAND_AREA ,
	LISTING_GROUP ,
	LISTING_ID ,
	LOUNGES ,
	PRICE_DISPLAY ,
	PROPERTY_TYPE ,
	REGION ,
	START_PRICE ,
	SUBURB,
	TITLE ,
	INSERTED_AT
FROM source_data
